name: Deploy Base Images
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Docker Login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build CPU Base 
      run: docker build -t deepquestai/deepstack-base:cpu-${{ github.run_id }} . -f Dockerfile.cpu
    - name: Build GPU Base
      run: docker build -t deepquestai/deepstack-base:gpu-${{ github.run_id }} . -f Dockerfile.gpu
    - name: Push CPU Base
      run: docker push deepquestai/deepstack-base:cpu-${{ github.run_id }}
    - name: Push GPU Base
      run: docker push deepquestai/deepstack-base:gpu-${{ github.run_id }}
      
